
CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    EMAIL VARCHAR2(100),
    SENHA VARCHAR2(100)
);

CREATE TABLE CONTAS (
    ID_CONTA NUMBER PRIMARY KEY,
    SALDO NUMBER(10,2)
);

CREATE TABLE TRANSACOES (
    ID_TRANSACAO NUMBER PRIMARY KEY,
    VALOR NUMBER(10,2),
    TIPO VARCHAR2(20)
);
